export const GET_TRANDING_MOVIES = "GET_TRANDING_MOVIES";
export const GET_POPUTAR_MOVIES = "GET_POPUTAR_MOVIES";
export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_MOVIE = "GET_MOVIE";
export const GET_SEARCH_MOVIE = "GET_SEARCH_MOVIE";
export const GET_CREDITS = "GET_CREDITS";
